baseurl = "https://taekolehmanphotography.com/"
languageCode = "en-us"
title = "Taeko Lehman Photography"
theme = "creative"
googleAnalytics = ""

[params]

	name = "Taeko Lehman Photography"
	description = "Atlanta, Georgia"

	# The path must be relative to the static folder
	favicon = "slr_camera.png"

	# Navigation
	[params.navigation]
		brand = "Taeko Lehman Photography"

		[params.navigation.links]
			about     = "About"
			services  = "Pricing"
			portfolio = "Portfolio"
      download = "Get your photos"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Taeko Lehman"
		subtitle   = "Photography"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Family Photographer"
		description = "Wife and mother of two wonderful and energetic boys. I am passionate about capturing those perfect moments of your family."
		buttonText  = "Book now!"
    img = "taeko.jpg"


	# Service section
	[params.services]
		headline = "Pricing"

        [[params.services.list]]
			icon = "fa-book"
			title = "Session Fee"
			description = "To book a session there is a non-refundable session fee of $100."

        [[params.services.list]]
            icon = "fa-cloud-download"
            title = "Digital Downloads"
            description = "Download your photos from the link below."

		[[params.services.list]]
            icon = "fa-picture-o"
            title = "Prints"
            description = "I offer prints online or after the review session.  Prices range from $300 to $1500 depending on size and number of prints."

        [[params.services.list]]
            icon = "fa-magic"
            title = "Touch ups"
            description = "Your prints will always have my professional hand removing spots and blemishes."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get your Photographs!"

		[params.aside.button]
			text = "Download photos"
			link = "//taekolehmanphotography.pixieset.com"

	# Contact section
	[params.contact]
		headline = "Book your session"
		description = "Please send me an email with details of the type of session in which you are interested. We will remain in contact to settle the time and location."
		email = "taekolehmanphotography.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
